package com.example.api.common.constraints;

import java.util.Set;

public class AppConstants {

    public static final String GEN_ERROR_CODE = "GENER_CODE";
    public static final String GEN_ERROR_DESC = "Unable to process your request,Please contact Customer Care for futher assistance or try again later";
    public static final String RESULT_CODE = "000000";
    public static final String RESULT_DESC = "SUCCESS";
    public static final String USERNAME = "userName";
    public static final String NA = "NA";
    public static final String SESSION_ID = "SESSION_ID";
    public static final String CUSTOMER_ID = "customerId";
    public static final String MW_RESULT = "0";
    public static final String APP_VERSION = "appVersion";
    public static final String DEVICE_ID = "deviceId";
    public static final String DEVICE_MODEL = "deviceModel";
    public static final String DEVICE_PLATFORM = "devicePlatform";
    public static final String END_TO_END_ID = "endToEndId";
    public static final String IP = "ipAddress";
    public static final String OS_VERSION = "osVersion";
    public static final String VENDOR_ID = "vendorId";
    public static final String CATEGORY_TYPE = "CATEGORY_TYPE";
    public static final String UPDATE_REQ_RR = "UPDATE_REQ_RR";
    public static final String SERVICE_VERSION = "1";
    public static final String RESPONSE = "RESPONSE";
    public static final String STATUS = "ACT";
    public static final String GUID = "guid";
    public static final String EMPTY = "";
    public static final String CUSTOMER_NO = "customerNumber";
    public static final String GID = "gId";
    public static final String USERNO = "userNo";
    public static final String BROWSER = "BROWSER";
    public static final String IP_ADDRESS = "IP_ADDRESS";
    public static final String EXCEPTION_MSG = "EXCEPTION_MSG";
    public static final String START_DATE = "startDate";
    public static final String END_DATE = "endDate";
    public static final String HOST_IP = "hostIP";
    public static final String BROWSER_KEY = "browser";
    public static final String Y = "Y";
    public static final String START_TIME = "startTime";
    public static final String END_TIME = "endTime";
    public static final String MWCODE = "mwCode";
    public static final String MWDESC = "mwdesc";
    public static final String CODE = "code";
    public static final String DESCRIPTION = "description";
    public static final String STATUS_KEY = "status";
    public static final String CATEGORY_CODE = "categoryCode";
    public static final String GEN_ERROR_DESC_AR = "Unable to process your request,Please contact customer care +974 xxxxx for further assistance or try again later";
    public static final String GEN_ERROR_DESC_FR = "Votre requete ne peut etre traitee! Merci de contacter notre service clientelle";
    public static final String UNIT = "unit";
    public static final String CHANNEL = "channel";
    public static final String ACCEPT_LANGUAGE = "Accept-Language";
    public static final String SERVICEID = "serviceId";
    public static final String SCREENID = "screenId";
    public static final String ACT = "ACT";
    public static final String SUCCESS_DESCRIPTION = "SUCCESS";
    public static final String SERVIC_TYPE = "MW";
    public static final String BRANCH_CODE = "branchCode";
    public static final String MODULE_ID = "moduleId";
    public static final String SUB_MODULE_ID = "subModuleId";
    public static final String SERVICE_ID = "serviceId";
    public static final String SCREEN_ID = "screenId";
    public static final String RESULT_ERROR_CODE = "000001";
    public static final String PENDING_LIST_SERVICE_ID = "APP_TXN";
    public static final String N = "N";
    public static final String DATE_WITH_AMPM = "dd/MM/yyyy hh:mm a";
    public static final String DATE = "dd/MM/yyyy";
    public static final String DEFAULT_LANG = "en";
    public static final String IB_CHANNEL_ID = "IB";
    public static final String CARD_STATEMENT = "cardStatement";
    public static final String CARD_SUMMARY = "cardSummary";
    public static final String DESCENDING = "desc";
    public static final String REQUEST_METHOD = "requestMethod";
    public static final String URL = "url";
    public static final String RESULT_ERROR_DESC = "FAILED";
    public static final String SUCCESS_CODE = "00000";
    public static final String GEN_ERROR_DESC_EN = "Unable to process your request,Please contact customer care +974 xxxxx for further assistance or try again later";
    public static final String FIRST_LOGIN = "firstLogin";
    public static final String FIRST_LOGIN_FAILD = "1";
    public static final String LOGIN_SUB_MODULEID = "LOGIN";
    public static final String CLIENT_SESSION_KEY = "clientSessionKey";
    public static final String SESSION_KEY  = "sessionKey";
    public static final String MB_CHANNEL_ID = "MB";
    public static final String RR_ID = "RR_ID";
    public static final String LANG = "lang";
    public static final String MW_REQUEST = "MW_REQUEST";
    public static final String MW_RESPONSE = "MW_RESPONSE";


}
