server:
  port: 9596

mock:
  enabled: true

app:
  mock:
    isMockResponse: true
  rate:
    digits: 6

spring:
  application:
    name: api-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://34.18.104.74:5432/dukhanbank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Poclab_123#
    hikari:
      max-lifetime: 540000
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.example.api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-service.log