server:
  port: 9596

mock:
  enabled: true

app:
  mock:
    isMockResponse: true
  rate:
    digits: 6

spring:
  application:
    name: api-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://34.18.104.74:5432/dukhanbank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Poclab_123#
    hikari:
      max-lifetime: 540000
  main:
    allow-bean-definition-overriding: true

# Statement Generation Configuration
statement:
  config:
    header:
      retail: config/headers-retail.json
      private: config/headers-private.json
    table:
      retail: config/table-columns-retail.json
      private: config/table-columns-private.json
  color:
    retail:
      primary: "#1E3A8A"
      secondary: "#3B82F6"
    private:
      primary: "#4B5563"
      secondary: "#6B7280"
  pdf:
    rows:
      per:
        page: 25
    margin:
      top: 72
      bottom: 72
      left: 72
      right: 72
    header:
      image:
        path: images/DukhanBank_Statement_Header.jpg
        private:
          path: images/Private_DukhanBank_Statement_Header.jpg
    footer:
      image:
        path: images/DukhanBank_Statement_Footer.jpg
        private:
          path: images/Private_DukhanBank_Statement_Footer.jpg
  excel:
    rows:
      per:
        page: 1000
    header:
      image:
        path: images/DukhanBank_Statement_Header.jpg
        private:
          path: images/Private_DukhanBank_Statement_Header.jpg
    footer:
      image:
        path: images/DukhanBank_Statement_Footer.jpg
        private:
          path: images/Private_DukhanBank_Statement_Footer.jpg

logging:
  level:
    root: INFO
    com.example.api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-service.log